# This file is in YAML format
# Declared variables to be passed into $/templates files
namespace: qe05

image:
  repository: 929380036510.dkr.ecr.us-east-1.amazonaws.com/darwin-opa
  tag: qa
  pullPolicy: Always

ingress:
  external:
    sslRedirect: "false"
    forceSslRedirect: "false"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 384Mi

# replicacount has no impact if autoscaling.enabled = true
autoscaling:
  enabled: false

env_vars:
  data:
    USERS_API_URL: "http://users-api"
    GROUPS_API_URL: "http://groups-api"
    COMPANY_API_URL: "http://company-api"
    AUTHORIZATION_API_URL: "http://authorization-api"
    CONTENTS_API_URL: "http://contents-api"
    KEYCLOAK_URL: "https://keycloak.qe05.darwin.wiley.host"
    LPI_API_URL: "http://lpi-api"

externalsecrets:
  refreshInterval: 1m
  secretCreationPolicy: Owner
  secretStoreName: eks-nonprod-us-secret-manager
  secretStoreType: ClusterSecretStore
  data:
  - keyValue: qe/darwin/secrets
    nameValue: USERS_API_KEY
    propertyValue: USERS_API_KEY
  - keyValue: qe/darwin/secrets
    nameValue: COMPANY_API_KEY
    propertyValue: COMPANY_API_KEY
  - keyValue: qe/darwin/secrets
    nameValue: GROUPS_API_KEY
    propertyValue: GROUPS_API_KEY
  - keyValue: qe/darwin/secrets
    nameValue: LPI_API_KEY
    propertyValue: LPI_API_KEY
  - keyValue: qe/darwin/secrets
    nameValue: AUTHORIZATION_API_KEY
    propertyValue: AUTHORIZATION_API_KEY
  - keyValue: qe/darwin/secrets
    nameValue: CONTENTS_API_KEY
    propertyValue: CONTENTS_API_KEY
